# Generated by Django 2.2.9 on 2022-02-23 21:33

import api.models
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Base',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('titulo', models.CharField(max_length=255)),
                ('data', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='jogos',
            fields=[
                ('base_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='api.Base')),
                ('nome', models.CharField(max_length=60)),
                ('descricao', models.TextField(blank=True, max_length=120)),
                ('category', models.CharField(choices=[('Ação', 'Ação'), ('Esportes', 'Esportes'), ('Terror', 'Terror'), ('RPG', 'RPG')], max_length=1)),
                ('status', models.CharField(choices=[('Em Estoque', 'Em Estoque'), ('Acabou', 'Acabou')], max_length=1)),
                ('preco', models.DecimalField(decimal_places=2, max_digits=20)),
                ('image', models.ImageField(blank=True, null=True, upload_to=api.models.upload_image_jogos)),
            ],
            options={
                'verbose_name': 'Jogo',
                'verbose_name_plural': 'Jogos',
            },
            bases=('api.base',),
        ),
    ]
